### ISSUE TITLE
support to 1.10-1.12

### ISSUE THREAD

**Issue by ProDash1998** [chaseoes/TF2#91]
Please add support to 1.12

**Comment by chaseoes** [comment]
What makes you think it doesn't work with 1.12?

**Comment by ProDash1998** [comment]
[TF2] Enabling TF2 v2.4-b46
[18:18:31 ERROR]: Error occurred while enabling TF2 v2.4-b46 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
        at me.chaseoes.tf2.MessagesFile.reloadMessages(MessagesFile.java:46) ~[?:?]
        at me.chaseoes.tf2.TF2.onEnable(TF2.java:113) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[hub1.jar:git-Spigot-7228328-14b597f]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [hub1.jar:git-Spigot-7228328-14b597f]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [hub1.jar:git-Spigot-7228328-14b597f]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [hub1.jar:git-Spigot-7228328-14b597f]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [hub1.jar:git-Spigot-7228328-14b597f]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [hub1.jar:git-Spigot-7228328-14b597f]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [hub1.jar:git-Spigot-7228328-14b597f]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [hub1.jar:git-Spigot-7228328-14b597f]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [hub1.jar:git-Spigot-7228328-14b597f]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [hub1.jar:git-Spigot-7228328-14b597f]

**Comment by ProDash1998** [comment]
https://youtu.be/MavJUGAOCqE
